"""Pipeline stage identifiers (must match NestJS Flat3dStage)."""
from enum import Enum

class Stage(str, Enum):
    INGEST = "INGEST"
    DWG_TO_DXF = "DWG_TO_DXF"
    DXF_PARSE = "DXF_PARSE"
    GEOMETRY_NORMALIZATION = "GEOMETRY_NORMALIZATION"
    SEMANTIC_EXTRACTION = "SEMANTIC_EXTRACTION"
    SCHEDULE_MATCHING = "SCHEDULE_MATCHING"
    FLAT_3D_GENERATION = "FLAT_3D_GENERATION"
    GLB_EXPORT = "GLB_EXPORT"
    GLB_VALIDATION = "GLB_VALIDATION"
    BROWSER_VERIFICATION = "BROWSER_VERIFICATION"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    FAILED = "FAILED"

class Confidence(str, Enum):
    CONFIRMED = "CONFIRMED"
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNRESOLVED = "UNRESOLVED"