import CompanyLogo from './CompanyLogo';

export interface PanelCompletionReportPreviewData {
  project: {
    code: string;
    name: string;
    client: string | null;
    locationRegion: string | null;
    monthYear: string | null;
  };
  panel: {
    id: string;
    name: string;
    panelType: string | null;
    voltageLevel: string | null;
  };
  reportStatus: string;
  reportStatusLabel: string;
  /** 'progress' while the panel is in execution; 'completion' only once wired + approved. */
  reportKind: 'progress' | 'completion';
  reportTitle: string;
  approval: {
    approved: boolean;
    approvedAt: string | null;
    approvedBy: { fullName: string } | null;
  };
  technicians: { fullName: string; username: string }[];
  technician: { fullName: string; username: string } | null;
  midChangeTechnician: { fullName: string; username: string } | null;
  contributions: {
    assignmentId: number;
    technician: { fullName: string; username: string };
    startedAt: string | null;
    endedAt: string | null;
    durationSeconds: number;
    durationHuman: string;
    cablesCompleted: number;
    sourceEndsCompleted: number;
    destinationEndsCompleted: number;
    progressBefore: number;
    progressAfter: number;
    sessionLog: { loginAt: string; logoutAt: string | null }[];
  }[];
  midChangeHistory: {
    action: string;
    technicianName: string;
    at: string | null;
    details: string;
  }[];
  supervisor: { fullName: string } | null;
  assignedBy: { fullName: string } | null;
  cables: {
    total: number;
    completed: number;
    remaining: number;
    openEndSource: number;
    openEndDestination: number;
  };
  wiring: {
    startedAt: string | null;
    completedAt: string | null;
    durationHuman: string;
  };
  sessionLog: { loginAt: string; logoutAt: string | null }[];
  totalWorkingHours: string;
  completionPercent: number;
  kpi: number;
  projectDurationDays: number;
  rework: { count: number; status: string; reason: string };
  technicianRemarks: string[];
  supervisorRemarks: string;
  generatedBy: string;
  generatedAt: string;
}

function fmt(dt: string | null) {
  if (!dt) return '—';
  return new Date(dt).toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

function parseSubstation(name: string, client: string | null) {
  const parts = name.split(/\s+[–—]\s+|\s+-\s+/).map(p => p.trim()).filter(Boolean);
  if (parts.length <= 1) return name.trim() || '—';
  let i = 1;
  const norm = (v: string) => v.trim().toUpperCase().replace(/\s+/g, ' ');
  if (parts[i] && client && norm(parts[i]) === norm(client)) i += 1;
  return parts[0];
}

function statusTone(status: string): string {
  switch (status) {
    case 'completed': return 'pcr-status--completed';
    default: return 'pcr-status--progress';
  }
}

function MetaGrid({ rows }: { rows: [string, string][] }) {
  return (
    <dl className="pcr-meta-grid">
      {rows.map(([label, value]) => (
        <div key={label} className="pcr-meta-item">
          <dt>{label}</dt>
          <dd title={value}>{value}</dd>
        </div>
      ))}
    </dl>
  );
}

export default function PanelCompletionReportPreview({ data }: { data: PanelCompletionReportPreviewData }) {
  const client = (data.project.client || '').trim() || '—';
  const substation = parseSubstation(data.project.name, data.project.client);
  const isCompletion = data.reportKind === 'completion';
  // Reference is built from what the reader can see — the internal frame id is never shown.
  const docRef = `DWES-${isCompletion ? 'PCR' : 'PPR'}-${`${data.project.code}-${data.panel.name}`
    .toUpperCase().replace(/[^A-Z0-9-]/g, '').slice(0, 30)}`;
  const approvalChip = data.approval?.approved
    ? `Approved${data.approval.approvedAt ? ` · ${fmt(data.approval.approvedAt)}` : ''}`
    : data.technician ? 'Pending supervisor approval' : 'Not yet assigned';
  const loginTimes = data.sessionLog.length
    ? data.sessionLog.map(s => fmt(s.loginAt)).join(' · ')
    : '—';
  const logoutTimes = data.sessionLog.length
    ? data.sessionLog.map(s => (s.logoutAt ? fmt(s.logoutAt) : 'Active')).join(' · ')
    : '—';
  const reworkLabel = data.rework.count > 0 ? `${data.rework.count} recorded` : 'None';
  const techRemarks = data.technicianRemarks.length ? data.technicianRemarks.join(' · ') : '—';
  const supRemarks = data.supervisorRemarks || data.rework.reason || '—';

  const personnel = [
    { label: 'Assigned technician(s)', name: data.technicians.map(t => t.fullName).join(', ') || '—' },
    { label: 'Production supervisor', name: data.supervisor?.fullName || '—' },
    { label: 'Report generated by', name: data.generatedBy },
  ];

  return (
    <div className="pcr-sheet" role="document" aria-label={`${data.reportTitle} preview`}>
      {/* Header band */}
      <header className="pcr-header">
        <div className="pcr-header-brand">
          <CompanyLogo variant="white" size="sm" className="shrink-0" />
          <div>
            <div className="pcr-header-company">Ingenious Network FZC</div>
            <div className="pcr-header-system">Digital Wiring Execution System</div>
          </div>
        </div>
        <div className="pcr-header-title">
          <div className="pcr-header-report-title">{data.reportTitle}</div>
          <div className="pcr-header-ref">Ref: {docRef}</div>
          <div className="pcr-header-ref">{fmt(data.generatedAt)}</div>
        </div>
      </header>

      {/* Project & panel identification */}
      <section className="pcr-section pcr-section--titled">
        <h3 className="pcr-section-title">Project &amp; panel</h3>
        <MetaGrid rows={[
          ['Project name', substation],
          ['Panel / subpanel', data.panel.name],
          ['Project number', data.project.code],
          ['Panel type', data.panel.panelType || '—'],
          ['Client', client],
          ['Voltage', data.panel.voltageLevel || '—'],
          ['Region / location', data.project.locationRegion || '—'],
          ['Assigned by', data.assignedBy?.fullName || '—'],
        ]} />
      </section>

      {/* Zone 3 — personnel */}
      <section className="pcr-personnel">
        {personnel.map(p => (
          <div key={p.label} className="pcr-person-block">
            <div className="pcr-person-label">{p.label}</div>
            <div className="pcr-person-name">{p.name}</div>
          </div>
        ))}
      </section>

      {/* Zone 4 — KPI cards */}
      <section className="pcr-kpi-row">
        <div className="pcr-kpi-lead">
          <div className="pcr-kpi-lead-value">{data.completionPercent}%</div>
          <div className="pcr-kpi-lead-label">Completion %</div>
          <progress className="pcr-progress" value={Math.min(data.completionPercent, 100)} max={100} />
        </div>
        <div className="pcr-kpi-card"><span className="pcr-kpi-value">{data.cables.total}</span><span className="pcr-kpi-label">Total cables</span></div>
        <div className="pcr-kpi-card pcr-kpi-card--green"><span className="pcr-kpi-value">{data.cables.completed}</span><span className="pcr-kpi-label">Completed</span></div>
        <div className="pcr-kpi-card"><span className="pcr-kpi-value">{data.cables.remaining}</span><span className="pcr-kpi-label">Remaining</span></div>
        <div className="pcr-kpi-card"><span className="pcr-kpi-value">{data.kpi}%</span><span className="pcr-kpi-label">Assigned cable KPI</span></div>
      </section>
      <section className="pcr-kpi-sub">
        <div className="pcr-kpi-card"><span className="pcr-kpi-value pcr-kpi-value--sm">{data.cables.openEndSource} / {data.cables.openEndDestination}</span><span className="pcr-kpi-label">Open-end (src / dst)</span></div>
        <div className="pcr-kpi-card"><span className="pcr-kpi-value pcr-kpi-value--sm">{reworkLabel}</span><span className="pcr-kpi-label">Rework</span></div>
        <div className={`pcr-status-pill ${statusTone(data.reportStatus)}`}>
          <span className="pcr-status-pill-label">Current status</span>
          <span className="pcr-status-pill-value">{data.reportStatusLabel}</span>
        </div>
      </section>

      {/* Execution timeline — no internal frame identifier */}
      <section className="pcr-section pcr-section--titled">
        <h3 className="pcr-section-title">Execution timeline &amp; duration</h3>
        <MetaGrid rows={[
          ['Wiring start', fmt(data.wiring.startedAt)],
          ['Wiring completion', fmt(data.wiring.completedAt)],
          ['Wiring duration', data.wiring.durationHuman || '—'],
          ['Total working hours', data.totalWorkingHours],
          ['Technician login(s)', loginTimes],
          ['Technician logout(s)', logoutTimes],
        ]} />
      </section>

      {(data.contributions || []).length > 0 && (
        <section className="pcr-section pcr-section--titled">
          <h3 className="pcr-section-title">Technician contribution &amp; Mid Change history</h3>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-left text-[10px] leading-4 text-slate-700">
              <thead>
                <tr className="border-b border-slate-300 bg-slate-50 text-[9px] uppercase tracking-wide text-slate-500">
                  <th className="px-2 py-1.5">Technician</th>
                  <th className="px-2 py-1.5">Work period</th>
                  <th className="px-2 py-1.5">Duration</th>
                  <th className="px-2 py-1.5">Cable contribution</th>
                  <th className="px-2 py-1.5">Progress</th>
                  <th className="px-2 py-1.5">Login / logout</th>
                </tr>
              </thead>
              <tbody>
                {data.contributions.map(contribution => (
                  <tr key={contribution.assignmentId} className="border-b border-slate-200 align-top">
                    <td className="max-w-[150px] whitespace-normal break-words px-2 py-2 font-semibold text-slate-900">
                      {contribution.technician.fullName}
                      {contribution.technician.username && <span className="block font-normal text-slate-500">@{contribution.technician.username}</span>}
                    </td>
                    <td className="px-2 py-2">{fmt(contribution.startedAt)}<span className="block text-slate-500">to {contribution.endedAt ? fmt(contribution.endedAt) : 'Active'}</span></td>
                    <td className="px-2 py-2">{contribution.durationHuman || '—'}</td>
                    <td className="px-2 py-2">
                      <strong>{contribution.cablesCompleted} cables</strong>
                      <span className="block text-slate-500">{contribution.sourceEndsCompleted} src · {contribution.destinationEndsCompleted} dst</span>
                    </td>
                    <td className="px-2 py-2">{contribution.progressBefore} → {contribution.progressAfter} complete</td>
                    <td className="px-2 py-2">
                      {contribution.sessionLog.length > 0
                        ? contribution.sessionLog.map((session, index) => (
                          <span className="block" key={`${contribution.assignmentId}-${index}`}>
                            {fmt(session.loginAt)} → {session.logoutAt ? fmt(session.logoutAt) : 'Active'}
                          </span>
                        ))
                        : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {(data.midChangeHistory || []).length > 0 && (
            <p className="mt-2 text-[10px] leading-4 text-slate-600">
              <strong>Mid Change audit:</strong>{' '}
              {data.midChangeHistory.map(entry => `${entry.technicianName || 'Technician'} · ${entry.action.replace(/_/g, ' ')} · ${fmt(entry.at)}`).join(' | ')}
            </p>
          )}
        </section>
      )}

      {/* Zone 6 — remarks */}
      <section className="pcr-section pcr-section--titled">
        <h3 className="pcr-section-title">Remarks &amp; notes</h3>
        <div className="pcr-remarks">
          <div className="pcr-remark-row">
            <span className="pcr-remark-label">Technician remarks</span>
            <span className="pcr-remark-text">{techRemarks}</span>
          </div>
          <div className="pcr-remark-row">
            <span className="pcr-remark-label">Supervisor remarks</span>
            <span className="pcr-remark-text">{supRemarks}</span>
          </div>
        </div>
      </section>

      {/* Approval & sign-off */}
      <section className="pcr-section pcr-section--titled">
        <h3 className="pcr-section-title">
          Approval &amp; sign-off
          <span className={`pcr-approval-chip${data.approval?.approved ? ' is-approved' : ''}`}>
            {approvalChip}
          </span>
        </h3>
        <div className="pcr-signatures">
          {[
            { title: 'Technician', name: data.technician?.fullName },
            {
              title: 'Production Supervisor',
              name: data.approval?.approvedBy?.fullName || data.supervisor?.fullName || data.generatedBy,
            },
            { title: 'Client / Management', name: '' },
          ].map(sig => (
            <div key={sig.title} className="pcr-sig-block">
              <div className="pcr-sig-title">{sig.title}</div>
              {sig.name && <div className="pcr-sig-name">{sig.name}</div>}
              <div className="pcr-sig-line" />
              <div className="pcr-sig-hint">Signature / Date</div>
            </div>
          ))}
        </div>
      </section>

      {/* What this document does and does not certify */}
      <p className="pcr-note">
        {isCompletion
          ? 'This panel is fully wired and supervisor-approved. Figures are taken from the recorded execution data and this document certifies completion.'
          : 'This panel is still in execution. Figures reflect progress recorded to date; a Project Completion Report is issued only after full wiring and supervisor approval.'}
      </p>

      {/* Footer */}
      <footer className="pcr-footer">
        <span>Confidential — Management and Client Review Copy</span>
        <span>Generated {fmt(data.generatedAt)}</span>
        <span>Page 1 of 1</span>
      </footer>
    </div>
  );
}
