import CompanyLogo from './CompanyLogo';

export interface PanelCompletionReportPreviewData {
  project: {
    code: string;
    name: string;
    client: string | null;
    locationRegion: string | null;
    monthYear: string | null;
  };
  panel: {
    id: string;
    name: string;
    panelType: string | null;
    voltageLevel: string | null;
  };
  reportStatus: string;
  reportStatusLabel: string;
  /** 'progress' while the panel is in execution; 'completion' only once wired + approved. */
  reportKind: 'progress' | 'completion';
  reportTitle: string;
  approval: {
    approved: boolean;
    approvedAt: string | null;
    approvedBy: { fullName: string } | null;
  };
  technicians: { fullName: string; username: string }[];
  technician: { fullName: string; username: string } | null;
  midChangeTechnician: { fullName: string; username: string } | null;
  contributions: {
    assignmentId: number;
    technician: { fullName: string; username: string };
    startedAt: string | null;
    endedAt: string | null;
    durationSeconds: number;
    durationHuman: string;
    cablesCompleted: number;
    sourceEndsCompleted: number;
    destinationEndsCompleted: number;
    progressBefore: number;
    progressAfter: number;
    sessionLog: { loginAt: string; logoutAt: string | null }[];
  }[];
  midChangeHistory: {
    action: string;
    technicianName: string;
    at: string | null;
    details: string;
  }[];
  supervisor: { fullName: string } | null;
  assignedBy: { fullName: string } | null;
  cables: {
    total: number;
    completed: number;
    remaining: number;
    openEndSource: number;
    openEndDestination: number;
  };
  wiring: {
    startedAt: string | null;
    completedAt: string | null;
    durationHuman: string;
  };
  sessionLog: { loginAt: string; logoutAt: string | null }[];
  totalWorkingHours: string;
  completionPercent: number;
  kpi: number;
  projectDurationDays: number;
  rework: { count: number; status: string; reason: string };
  technicianRemarks: string[];
  supervisorRemarks: string;
  generatedBy: string;
  generatedAt: string;
}

function fmt(dt: string | null) {
  if (!dt) return '—';
  return new Date(dt).toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

function parseSubstation(name: string, client: string | null) {
  const parts = name.split(/\s+[–—]\s+|\s+-\s+/).map(p => p.trim()).filter(Boolean);
  if (parts.length <= 1) return name.trim() || '—';
  let i = 1;
  const norm = (v: string) => v.trim().toUpperCase().replace(/\s+/g, ' ');
  if (parts[i] && client && norm(parts[i]) === norm(client)) i += 1;
  return parts[0];
}

function statusTone(status: string): string {
  switch (status) {
    case 'completed': return 'pcr-status--completed';
    default: return 'pcr-status--progress';
  }
}

export default function PanelCompletionReportPreview({ data }: { data: PanelCompletionReportPreviewData }) {
  const client = (data.project.client || '').trim() || '—';
  const substation = parseSubstation(data.project.name, data.project.client);
  const isCompletion = data.reportKind === 'completion';
  // Reference is built from what the reader can see — the internal frame id is never shown.
  const docRef = `DWES-${isCompletion ? 'PCR' : 'PPR'}-${`${data.project.code}-${data.panel.name}`
    .toUpperCase().replace(/[^A-Z0-9-]/g, '').slice(0, 30)}`;
  const loginTimes = data.sessionLog.length
    ? data.sessionLog.map(s => fmt(s.loginAt)).join(' · ')
    : '—';
  const logoutTimes = data.sessionLog.length
    ? data.sessionLog.map(s => (s.logoutAt ? fmt(s.logoutAt) : 'Active')).join(' · ')
    : '—';
  const reworkLabel = data.rework.count > 0 ? `${data.rework.count} recorded` : 'None';

  const personnel = [
    { label: 'Assigned technician(s)', name: data.technicians.map(t => t.fullName).join(', ') || '—' },
    { label: 'Production supervisor', name: data.supervisor?.fullName || '—' },
    { label: 'Report generated by', name: data.generatedBy },
  ];

  return (
    <div className="pcr-sheet" role="document" aria-label="Panel Report preview">
      {/* Zone A — compact masthead */}
      <header className="pcr-masthead">
        <div className="pcr-masthead-brand">
          <CompanyLogo variant="white" size="sm" className="shrink-0" />
          <div className="pcr-masthead-brand-text">
            <div className="pcr-masthead-company">Ingenious Network FZC</div>
            <div className="pcr-masthead-system">Digital Wiring Execution System</div>
          </div>
        </div>
        <div className="pcr-masthead-title">
          <div className="pcr-masthead-report-title">Panel Report</div>
          <div className="pcr-masthead-ref">Ref: {docRef}</div>
          <div className="pcr-masthead-ref">Generated {fmt(data.generatedAt)}</div>
        </div>
      </header>

      {/* Zone B — Project & Panel (4-col box matrix) */}
      <section className="pcr-block">
        <h3 className="pcr-block-title">Project &amp; Panel</h3>
        <div className="pcr-grid pcr-grid--4">
          <div className="pcr-cell"><span className="pcr-cell-label">Project name</span><span className="pcr-cell-value" title={substation}>{substation}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Panel / subpanel</span><span className="pcr-cell-value" title={data.panel.name}>{data.panel.name}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Project number</span><span className="pcr-cell-value">{data.project.code}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Panel type</span><span className="pcr-cell-value">{data.panel.panelType || '—'}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Client</span><span className="pcr-cell-value" title={client}>{client}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Voltage</span><span className="pcr-cell-value">{data.panel.voltageLevel || '—'}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Region / location</span><span className="pcr-cell-value">{data.project.locationRegion || '—'}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Assigned by</span><span className="pcr-cell-value">{data.assignedBy?.fullName || '—'}</span></div>
        </div>
      </section>

      {/* Zone C — Responsibility (3 equal boxes) */}
      <section className="pcr-block">
        <h3 className="pcr-block-title">Responsibility</h3>
        <div className="pcr-grid pcr-grid--3">
          {personnel.map(p => (
            <div key={p.label} className="pcr-cell">
              <span className="pcr-cell-label">{p.label}</span>
              <span className="pcr-cell-value" title={p.name}>{p.name}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Zone D — KPI (5 equal compact cards) */}
      <section className="pcr-block">
        <h3 className="pcr-block-title">Key Performance Indicators</h3>
        <div className="pcr-grid pcr-grid--5">
          <div className="pcr-kpi-cell pcr-kpi-cell--accent">
            <span className="pcr-kpi-value">{data.completionPercent}%</span>
            <span className="pcr-kpi-label">Completion %</span>
            <progress className="pcr-kpi-bar" value={Math.min(data.completionPercent, 100)} max={100} />
          </div>
          <div className="pcr-kpi-cell"><span className="pcr-kpi-value">{data.cables.total}</span><span className="pcr-kpi-label">Total cables</span></div>
          <div className="pcr-kpi-cell"><span className="pcr-kpi-value">{data.cables.completed}</span><span className="pcr-kpi-label">Completed</span></div>
          <div className="pcr-kpi-cell"><span className="pcr-kpi-value">{data.cables.remaining}</span><span className="pcr-kpi-label">Remaining</span></div>
          <div className="pcr-kpi-cell"><span className="pcr-kpi-value">{data.kpi}%</span><span className="pcr-kpi-label">Assigned cable KPI</span></div>
        </div>
      </section>

      {/* Zone E — Operational result (3 equal boxes) */}
      <section className="pcr-block">
        <h3 className="pcr-block-title">Operational Result</h3>
        <div className="pcr-grid pcr-grid--3">
          <div className="pcr-cell">
            <span className="pcr-cell-label">Open-end source / destination</span>
            <span className="pcr-cell-value">{data.cables.openEndSource} / {data.cables.openEndDestination}</span>
          </div>
          <div className="pcr-cell">
            <span className="pcr-cell-label">Rework</span>
            <span className="pcr-cell-value">{reworkLabel}</span>
          </div>
          <div className={`pcr-cell pcr-cell--status ${statusTone(data.reportStatus)}`}>
            <span className="pcr-cell-label">Current status</span>
            <span className="pcr-cell-value">{data.reportStatusLabel}</span>
          </div>
        </div>
      </section>

      {/* Zone F — Execution timeline & duration (2-col matrix) */}
      <section className="pcr-block">
        <h3 className="pcr-block-title">Execution Timeline &amp; Duration</h3>
        <div className="pcr-grid pcr-grid--2">
          <div className="pcr-cell"><span className="pcr-cell-label">Wiring start</span><span className="pcr-cell-value">{fmt(data.wiring.startedAt)}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Wiring completion</span><span className="pcr-cell-value">{fmt(data.wiring.completedAt)}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Wiring duration</span><span className="pcr-cell-value">{data.wiring.durationHuman || '—'}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Total working hours</span><span className="pcr-cell-value">{data.totalWorkingHours}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Technician login(s)</span><span className="pcr-cell-value">{loginTimes}</span></div>
          <div className="pcr-cell"><span className="pcr-cell-label">Technician logout(s)</span><span className="pcr-cell-value">{logoutTimes}</span></div>
        </div>
        {(data.midChangeHistory || []).length > 0 && (
          <div className="pcr-midchange-note">
            <span className="pcr-cell-label">Mid change history</span>
            <span className="pcr-cell-value">
              {data.midChangeHistory.map(entry => `${entry.technicianName || 'Technician'} · ${entry.action.replace(/_/g, ' ')} · ${fmt(entry.at)}`).join(' | ')}
            </span>
          </div>
        )}
      </section>

      {(data.contributions || []).length > 0 && (
        <section className="pcr-block">
          <h3 className="pcr-block-title">Technician Contribution &amp; Mid Change History</h3>
          <div className="pcr-table-wrap">
            <table className="pcr-table">
              <thead>
                <tr>
                  <th>Technician</th>
                  <th>Work period</th>
                  <th>Duration</th>
                  <th>Cable contribution</th>
                  <th>Progress</th>
                  <th>Login / logout</th>
                </tr>
              </thead>
              <tbody>
                {data.contributions.map(contribution => (
                  <tr key={contribution.assignmentId}>
                    <td className="pcr-table-tech">
                      {contribution.technician.fullName}
                      {contribution.technician.username && <span className="pcr-table-username">@{contribution.technician.username}</span>}
                    </td>
                    <td>{fmt(contribution.startedAt)}<span className="pcr-table-sub">to {contribution.endedAt ? fmt(contribution.endedAt) : 'Active'}</span></td>
                    <td>{contribution.durationHuman || '—'}</td>
                    <td>
                      <strong>{contribution.cablesCompleted} cables</strong>
                      <span className="pcr-table-sub">{contribution.sourceEndsCompleted} src · {contribution.destinationEndsCompleted} dst</span>
                    </td>
                    <td>{contribution.progressBefore} → {contribution.progressAfter} complete</td>
                    <td>
                      {contribution.sessionLog.length > 0
                        ? contribution.sessionLog.map((session, index) => (
                          <span className="block" key={`${contribution.assignmentId}-${index}`}>
                            {fmt(session.loginAt)} → {session.logoutAt ? fmt(session.logoutAt) : 'Active'}
                          </span>
                        ))
                        : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      {/* Zone G — remarks (presentation removed; underlying data preserved) */}

      {/* Zone H — approval & sign-off (presentation removed; underlying data preserved) */}

      {/* Report footer */}
      <footer className="pcr-footer">
        <span>Confidential — Management and Client Review Copy</span>
        <span>Generated {fmt(data.generatedAt)}</span>
        <span>Page 1 of 1</span>
      </footer>
    </div>
  );
}
